
@contentType = application/json
@baseUrlDetailsById = http://localhost:4000/movies/550
@baseUrlTranslationById = http://localhost:4000/movies/550/translations


### GET Movies Details by ID      
GET {{baseUrlDetailsById}}
Content-Type: {{contentType}}

### GET Movies Transalation by ID      
GET {{baseUrlTranslationById}}
Content-Type: {{contentType}}
