
version: "3.1"
services:
  db:
    image: mongo:4.2
    container_name: db-gupy
    restart: always
    expose:
    - "27017"
    ports:
      - "27017:27017"
    environment:
      DBA_PASSWORD: 12345
      DBA_USER: user
      DBA_DB: db-gupy
      DB_HOST: db-gupy
